### ISSUE TITLE
Super fast run and super high AIC/low likelihood sometimes

### ISSUE THREAD

**Issue by HeatherKates** [thej022214/corHMM#25]
Hi there,
Every once in a while when I run corHMM, corHMM() finishes/exits immediately after printing `Beginning thorough optimization search -- performing 0 random restarts`
There's no error, but the AICc value is enormous and the loglik is tiny. In the past, rerunning has solved the problem but at the moment this happens for a few of my models every time I run them. Any idea why this would be? I'm successfully running other instances that are very similar - e.g. the same model and tip states but a slightly different tree, or the same tree and tip states but a model with one more rate category. Seems that what "fails" is random.

[Rosids.SpeciesBackbone.ultrametric.tree.txt](https://github.com/thej022214/corHMM/files/6825322/Rosids.SpeciesBackbone.ultrametric.tree.txt)
[Nitfix.statematrix.terms.NAs.withoutgroups.edit.csv.txt](https://github.com/thej022214/corHMM/files/6825325/Nitfix.statematrix.terms.NAs.withoutgroups.edit.csv.txt)

My run command is:
```
library(corHMM)
tipstate_matrix <- read.csv("Nitfix.statematrix.terms.NAs.withoutgroups.edit.csv",header=TRUE)
tree <- read.tree("Rosids.SpeciesBackbone.ultrametric.tree")
Species.HR4 <- corHMM(tree,tipstate_matrix,4,rate.mat=NULL,
                     node.states="none",fixed.nodes=FALSE,p=NULL,root.p=NULL,
                     ip=NULL,nstarts=0,n.cores=1,get.tip.states=FALSE,lewis.asc.bias=FALSE,
                     lower.bound = 1e-9,upper.bound = 100)
save.image("Species.HR4.RData")
```
Input files are attached. Thanks!

**Comment by jboyko** [comment]
Hi Heater,

That's quite odd. I ran through a few iterations of the dataset and model you provided and things seemed to be functioning normally. However, I did notice that you had branch lengths of length 0. As a first try, I'd suggest adding 1e-5 to those branches. If that doesn't do work, let us know and we can keep digging.

`tree$edge.length[tree$edge.length < 1e-5] <- 1e-5`

**Comment by HeatherKates** [comment]
Weird! I'm using corHMM v 2.5 - is there a more recent version I'm missing? I'll do the branch length adjustment, thanks for the tip - I'd be surprised if it's the issue here though as I said this tree works as input all the time in other instances.

**Comment by jboyko** [comment]
Oh, one other thing to explore would be the initial parameters! I missed the part in your title that said "super fast run" which would suggest an optimization problem. This is possibly occurring because of a constraint we put on default rate matrices. The constraint ensures that rate classes always have the same order (R1 > R2 > R3 etc.). There are a few reasons to do this so I wouldn't suggest turning it off (one reason is so that optimizers don't get stuck bouncing between two sets of parameters with the same likelihood, but one is R1 > R2 ang the other is R2 > R1). But, one possible way around this would be to set initial parameters that abide by this constraint. Currently, the initial parameters that I get when running corHMM are:
`c(0.0019520527, 0.0003789202, # transitions within R1
  0.0014249024, 0.0006540929, # transitions within R2
  0.0002228646, 0.0020804356, # transitions within R3
  0.0019312095, 0.0003456114, # transitions within R4
  0.0004849711, 0.0051791016, 0.0007108292, 0.0003202395, 0.0034379930, 0.0037922730, 0.0001342925, 0.0008971168, 0.0003326416, 0.0002712189, 0.0051542196, 0.0005375696) # transitions between rateclasses`

So another possible solution would be to tweak these such that they meet the constraint (this is something that should be done internally in corHMM, so I'll work on fixing it). 

`ip <- c(0.0019520527, 0.0003789202, # transitions within R1
        0.0018312095, 0.0003456114, # transitions within R4
        0.0014249024, 0.0006540929, # transitions within R2
        0.0002228646, 0.0020804356, # transitions within R3
        0.0004849711, 0.0051791016, 0.0007108292, 0.0003202395, 0.0034379930, 0.0037922730, 0.0001342925, 0.0008971168, 0.0003326416, 0.0002712189, 0.0051542196, 0.0005375696) # transitions between rateclasses

Species.HR4 <- corHMM(tree,tipstate_matrix,4,rate.mat=NULL,
                      node.states="none",fixed.nodes=FALSE,p=NULL,root.p=NULL,
                      ip=ip,nstarts=0,n.cores=1,get.tip.states=FALSE,lewis.asc.bias=FALSE,
                      lower.bound = 1e-9,upper.bound = 100)
`
But see if the above code can help corHMM run more smoothly.

**Comment by jboyko** [comment]
I've also changed things for the github version of corHMM. So if you install the github version the ip should be in an agreeable order without the user needing to input the parameters themselves.
